# Generated by Django 4.2.14 on 2024-07-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_abastecimento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tanque",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Bomba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bomba_utilizada",
                    models.CharField(
                        choices=[
                            ("GASOLINA 1", "Gasolina bomba 1"),
                            ("GASOLINA 2", "Gasolina bomba 2"),
                            ("DIESEL 1", "Diesel bomba 1"),
                            ("DIESEL 2", "Diesel bomba 2"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tanque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bombas",
                        to="app_abastecimento.tanque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abastecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "quantidade_litros",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "valor_abastecido",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("imposto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bomba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abastecimentos",
                        to="app_abastecimento.bomba",
                    ),
                ),
            ],
        ),
    ]
