# Generated by Django 4.2.14 on 2024-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_abastecimento", "0002_alter_tanque_data_bomba_abastecimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomba",
            name="bomba_utilizada",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tanque",
            name="tipo_combustivel",
            field=models.CharField(max_length=50),
        ),
    ]
